### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LaquanFinema** [E1Bos/VALocker#9] opened 2024-08-15 23:56 UTC
**Describe the bug**
The exe fails to run and returns an error as shown below.

**To Reproduce**
Every time I double click to run ther executable, nothing happens for a second and then the error window appears.

**Expected behavior**
In previous versions the ui would open when the exe was run

**Screenshots**
The error window:
![VALocker](https://github.com/user-attachments/assets/1c8ceb41-128a-4a36-9c31-e1f55198194c)

The line that I believe is refferenced in the error:
![image](https://github.com/user-attachments/assets/af44aa23-b2bf-497e-945b-f27582a2c83a)

**Program Information:**
 - Version 2.1.3

**Additional context**
Pretty sure this is a software issue but it could be my fault, hope the above was helpful.

**Comment by E1Bos** [comment] 2024-08-16 00:34
Thank you for the report,

I've started investigating the issue and I think I've found the root cause. I'll respond with more details when I've fully fixed the issue.

**Comment by E1Bos** [comment] 2024-08-16 01:20
Hello, I think I've solved the issue.

The issue came from the Settings file not having its version (`1.0.1`) updated when I added the new `fastModeTimings` dict. It would pass the update check, and the version check, and since fastModeTimings was previously a list, it would return a valid value so it wouldn't be replaced with the default "If all else fails" value. this fix has been rolled out and should be fixed for all VALocker 2.1.3.

**Closed** 2024-08-16 01:34 UTC
